name: cdk-nag
on:
  push:
    branches:
      - main

jobs:
  cdk-nag:
    runs-on: ubuntu-latest
    steps:
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: '1.16.2'
          working_dir: 'deploy'

