name: NAG Check

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install -g aws-cdk
        pip install -r deploy/requirements.txt
    - name: Build
      run: |
        cd deploy
        cdk synth
    - name: Stelligent cfn_nag
      uses: stelligent/cfn_nag@v0.8.6
      with:
        input_path: deploy/cdk.out/
        extra_args: -t ..*\.template\.json

