name: cdk-nag
on:
  push:
    branches:
      - main

jobs:
  cdk-nag:
    runs-on: ubuntu-latest
    steps:
      - name: Stelligent cfn_nag
        uses: stelligent/cfn_nag@v0.8.6
        with:
            # Where cfn_nag_scan should scan for violations (default: $GITHUB_WORKSPACE).
            input_path: deploy# optional, default is .

