name: NAG Check

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install -g aws-cdk
        npm install -g cdk-nag
        pip install -r deploy/requirements.txt
    - name: Build
      run: |
        cd deploy
        cdk synth
    - name: Test
      run: |
        cfn_nag_scan --input-path deploy/cdk.out
