name: CDK Deploy

on:
  push:
    branches:
      - main
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

env:
  AWS_REGION : ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID : ${{ vars.AWS_ACCOUNT_ID }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  ZONE_NAME: ${{ vars.ZONE_NAME }}
  APP_PATH: ${{ vars.APP_PATH }}
  STACK_NAME: ${{ vars.STACK_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionCDKRole
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install -g aws-cdk
        pip install -r deploy/requirements.txt
    - name: Bootstrap
      run: |
        cd deploy
        cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}
    - name: Build
      run: |
        cd deploy
        cdk deploy --require-approval never
